### PR TITLE
CI: use a stable & working release

### PR DESCRIPTION
**Pull request by bilelmoussaoui**
cc @aleixpol

### CODE REVIEW

**Comment by aleixpol** [comment]
the yml looks much better like that. Can you address teh error the CI found?

**Comment by bilelmoussaoui** [comment]
I don't think that's an issue on the config itself, please re-run the action from the Action/Details page as I don't have access to that.

**Comment by aleixpol** [comment]
Re-ran it, gives the same. Maybe we can add some verbosity so it gives some information of what it's doing?

The json file here is 87 lines.

**Comment by bilelmoussaoui** [comment]
> Re-ran it, gives the same. Maybe we can add some verbosity so it gives some information of what it's doing?
> 
> The json file here is 87 lines.

The issue is caused by https://github.com/aleixpol/maliit-flatpak/blob/master/com.github.maliit.keyboard.json#L79-L83 which is not a valid json per nodejs is `JSON.parse()`

**Comment by aleixpol** [comment]
Uh you changed so much the document that I'm not sure what changed. Merging anyway, thanks for the fix.

**Comment by aleixpol** [comment]
And thanks for looking into it, will see how we can include it in my workflow!

**Comment by bilelmoussaoui** [comment]
> Uh you changed so much the document that I'm not sure what changed. Merging anyway, thanks for the fix.

I've just moved the desktop file to a separate source, the rest is mostly a json.parse -> json.dump to "prettify it". No problem, let me know if I can improve the action more to fit other potential use cases

**Pull request merged**
